<a href="https://colab.research.google.com/github/Nidhi89717/ML/blob/main/02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy <br>
https://numpy.org/

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
print(mylist)
type(mylist)

[1, 2, 3]


list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [7]:
my_arr = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
print(np.linspace(0,10,3))          # (10 - 1)/ (3-1)
len(np.linspace(0,10,3))

[ 0.  5. 10.]


3

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.67505255])

In [26]:
np.random.rand(2,3)

array([[0.91861916, 0.68125611, 0.39198582],
       [0.70169142, 0.79405531, 0.99414467]])

In [27]:
np.random.randn(10)

array([-1.28256418, -1.59946577, -1.88024952,  1.4557543 , -0.22949191,
       -0.7583907 , -1.34575739, -0.99372553,  0.12815845,  0.19428737])

In [28]:
np.random.randn(3,3)

array([[-1.59607796,  0.36504029, -0.97117724],
       [ 0.57254977, -0.20583049,  0.44592908],
       [-0.09056343,  0.31607024, -0.65743202]])

In [31]:
np.random.randint(0,101,10)

array([11, 27, 82, 72, 31, 53, 67, 43, 65, 62])

In [32]:
np.random.randint(0,101,(4,5))

array([[24, 33, 89, 24, 44],
       [65, 56,  0, 76, 76],
       [29, 21, 45, 34, 94],
       [90, 86, 58, 92, 62]])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr = np.arange(0,25)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr = np.random.randint(0,101,10)

In [37]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [38]:
ranarr.max()

99

In [39]:
ranarr.min()

2

In [40]:
ranarr.argmax()

5

In [41]:
ranarr.argmin()

7

In [44]:
ranarr.dtype

dtype('int64')

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.shape

(25,)

In [53]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape                           # shape is an attribute not a method so dont use brackets

(5, 5)

In [56]:
arr = arr.reshape(1,25)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
arr.shape

(1, 25)