<a href="https://colab.research.google.com/github/Nidhi89717/ML/blob/main/03_NumPy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##NumPy Indexing and Selection

In [65]:
import numpy as np

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8]

8

In [69]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[:5]

array([0, 1, 2, 3, 4])

In [71]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape.That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list.With NumPy arrays, you can broadcast a single value across a larger set of values:

In [9]:
arr[:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
slice_of_arr = arr[0:5]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)
The general format is **arr_2d[row][col]** or **arr_2d[row,col]**

In [26]:
arr_2d = np.array([[5,10,15], [20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d.shape

(3, 3)

In [40]:
arr_2d[1]  # print only rows

array([20, 25, 30])

In [39]:
arr_2d[:,[0]]  # print only columns

array([[ 5],
       [20],
       [35]])

In [37]:
arr_2d[:,[1]]

array([[10],
       [25],
       [40]])

In [38]:
arr_2d[:,[2]]

array([[15],
       [30],
       [45]])

In [41]:
arr_2d[1,1]    # same as arr_2d[1][1]

25

In [42]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [45]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [50]:
bool_arr = arr > 4

In [51]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [52]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])